# Generated by Django 4.1.3 on 2022-12-03 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contas",
            fields=[
                (
                    "id_conta",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo_conta", models.CharField(max_length=50)),
                ("nome_conta", models.CharField(max_length=255)),
                ("saldo_inicial", models.FloatField()),
            ],
        ),
    ]
